<table width="100%" bgcolor="#DDDDDD" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<th align="left" valign="middle" class="zarko">&nbsp;&nbsp;&nbsp;phpCDs :: Online Music Inventory</th>
		<th align="right" valign="middle" class="zarko"><a href="/phpCDs/cart.php" class="zarko">View Cart</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#187;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/phpCDs/auth/insert.php" class="zarko">Update Page</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#187;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/phpCDs/welcome2.php" class="zarko">Help :: About</a>&nbsp;&nbsp;&nbsp;</th>
	</tr>
</table>
